### ISSUE TITLE
Test are broken in Travis with node 8 issue with error "Uncaught Error: socket hang up"

### ISSUE THREAD

**Issue by jaakkos** [jaakkos/winston-logstash#49]
```bash
> winston-logstash@0.4.0 test /home/travis/build/jaakkos/winston-logstash
> node_modules/mocha/bin/mocha test/*_test.js
  winston-logstash transport
    with logstash server
      ✓ send logs over TCP as valid json
      ✓ send each log with a new line character
      ✓ send with different log levels
      ✓ send with overrided meta data
    with secured logstash server
      ✓ send logs over SSL secured TCP as valid json
      1) send logs over SSL secured TCP as valid json with SSL verification
      ✓ logstash transport receive an error when there is a connection error different from ECONNREFUSED
    without logstash server
      ✓ fallback to silent mode if logstash server is down (403ms)
      ✓ emit an error message when it fallback to silent mode (403ms)
  8 passing (864ms)
  1 failing
  1) winston-logstash transport
       with secured logstash server
         send logs over SSL secured TCP as valid json with SSL verification:
     Uncaught Error: socket hang up
      at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by djMax** [comment]
I've seen this on some other projects with certain certs. I believe node8 removes some elliptic curves. Are the tests making the server side of it too?

**Comment by djMax** [comment]
Looks like that's not it. Researching.

**Comment by djMax** [comment]
Something to do with cert verification - if I set rejectUnauthorized to false in the server creation, it works fine. So it would stand to reason the client cert isn't validating, but it's a bit of a blackhole on the key material at the moment (for me).

**Comment by djMax** [comment]
Where is the client certificate used? I see the server using the client CA and the client using the server CA, but nowhere do I see it loading the client cert.
